DROP TABLE IF EXISTS groups, students, courses, professors, group_course, professor_course,
    auditories, lessons, time_periods, times,
    schedule
    CASCADE;

CREATE TABLE groups
(
    group_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name VARCHAR(5) NOT NULL UNIQUE
);

CREATE TABLE students
(
    student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id   INTEGER     NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name  VARCHAR(50) NOT NULL,
    FOREIGN KEY (group_id) REFERENCES groups (group_id)
);

CREATE TABLE courses
(
    course_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name        VARCHAR(50)  NOT NULL UNIQUE,
    course_description VARCHAR(150) NOT NULL
);

CREATE TABLE professors
(
    professor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name   VARCHAR(50) NOT NULL,
    last_name    VARCHAR(50) NOT NULL
);

CREATE TABLE group_course
(
    group_id  INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    FOREIGN KEY (group_id) REFERENCES groups (group_id) ON DELETE CASCADE,
    FOREIGN KEY (course_id) REFERENCES courses (course_id) ON DELETE CASCADE
);

CREATE TABLE professor_course
(
    professor_id INTEGER NOT NULL,
    course_id    INTEGER NOT NULL,
    FOREIGN KEY (professor_id) REFERENCES professors (professor_id) ON DELETE CASCADE,
    FOREIGN KEY (course_id) REFERENCES courses (course_id) ON DELETE CASCADE
);

CREATE TABLE auditories
(
    auditory_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auditory_location VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE time_periods
(
    time_period_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_hour     TIMESTAMP NOT NULL,
    end_hour       TIMESTAMP NOT NULL
);

CREATE TABLE times
(
    time_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date           DATE    NOT NULL,
    time_period_id INTEGER NOT NULL,
    FOREIGN KEY (time_period_id) REFERENCES time_periods (time_period_id)
);

CREATE TABLE lessons
(
    lesson_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id    INTEGER NOT NULL,
    professor_id INTEGER NOT NULL,
    group_id     INTEGER NOT NULL,
    auditory_id  INTEGER NOT NULL,
    FOREIGN KEY (course_id) REFERENCES courses (course_id),
    FOREIGN KEY (professor_id) REFERENCES professors (professor_id),
    FOREIGN KEY (group_id) REFERENCES groups (group_id),
    FOREIGN KEY (auditory_id) REFERENCES auditories (auditory_id)
);

CREATE TABLE schedule
(
    time_id   INTEGER NOT NULL,
    lesson_id INTEGER NOT NULL,
    FOREIGN KEY (time_id) REFERENCES times (time_id) ON DELETE CASCADE,
    FOREIGN KEY (lesson_id) REFERENCES lessons (lesson_id) ON DELETE CASCADE
);